[project]
name = "posthog"
version = "0.0.0"
requires-python = "==3.13.13"
dependencies = [
    "celery==5.6.3",
    "django~=5.2.0",
    "psycopg2-binary==2.9.10",
    "psycopg[binary]==3.2.4",
    "pymssql==2.3.5",
    "pymysql==1.1.1",
    "pymongo==4.13.2",
    "redis==5.3.1",
]

[dependency-groups]
dev = [
    "types-pymysql==1.1.0.20240524",
]
